// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Er6H2b6Fc1ptSccg_Drg-U6iWyHaGHo',
    appId: '1:619946128504:web:40d5cb143608d41c8c298d',
    messagingSenderId: '619946128504',
    projectId: 'aiproject-601cb',
    authDomain: 'aiproject-601cb.firebaseapp.com',
    databaseURL: 'https://aiproject-601cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aiproject-601cb.appspot.com',
    measurementId: 'G-DH28YQS7G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30Gz3cZ0pCtVmJ8mYF-aW7qGc9QS7tMg',
    appId: '1:619946128504:android:c9b805bd8fed5a1b8c298d',
    messagingSenderId: '619946128504',
    projectId: 'aiproject-601cb',
    databaseURL: 'https://aiproject-601cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aiproject-601cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJyQtsoLc7SUniReNBKHSDDCaJkBW9Aw',
    appId: '1:619946128504:ios:3465205d1db302c98c298d',
    messagingSenderId: '619946128504',
    projectId: 'aiproject-601cb',
    databaseURL: 'https://aiproject-601cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aiproject-601cb.appspot.com',
    androidClientId: '619946128504-0i7hmc423ad16m09aldp7bvmcv717jfa.apps.googleusercontent.com',
    iosClientId: '619946128504-l8jbepk0a7iqidlmf5mh6kqbvbm12uah.apps.googleusercontent.com',
    iosBundleId: 'com.example.refmanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJyQtsoLc7SUniReNBKHSDDCaJkBW9Aw',
    appId: '1:619946128504:ios:3465205d1db302c98c298d',
    messagingSenderId: '619946128504',
    projectId: 'aiproject-601cb',
    databaseURL: 'https://aiproject-601cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aiproject-601cb.appspot.com',
    androidClientId: '619946128504-0i7hmc423ad16m09aldp7bvmcv717jfa.apps.googleusercontent.com',
    iosClientId: '619946128504-l8jbepk0a7iqidlmf5mh6kqbvbm12uah.apps.googleusercontent.com',
    iosBundleId: 'com.example.refmanage',
  );
}
